apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: merit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: apache-container
          image: merit237/new-app:v${BUILD_NUMBER}
         
              
